### PR TITLE
fix invalid regex on windows due to path.sep.

### LINKED ISSUE #16: path.sep creates an invalid regex on windows.
```
G:\src\cykik\node_modules\node-sass-package-importer\dist\index.js:40
  this.matchPackageUrl = new RegExp(("^~(?!" + (path.sep) + ")"));
                         ^
SyntaxError: Invalid regular expression: /^~(?!\)/: Unterminated group
```

as you can tell from the syntax error path.sep on windows is a .

the below seems to work fine on win 10.

```
  var pathSep = (path.sep === '/')  ? path.sep : '\\\\';  
  this.matchPackageUrl = new RegExp("^~(?!" + (pathSep) + ")");
```

### PR DESCRIPTION
**Pull request by dopry**
closes #16

### CODE REVIEW

**Review by maoberlehner — CHANGES_REQUESTED** [review]
Thank you for your pull request.
Please fix linting errors
- `const` instead of `let`
- es6 template strings (backticks) instead of double quotes

Although, as far as I know, there are only two types of path separators (windows style and unix style), I think escaping regex special characters in general would be the cleanest solution.

`const pathSep = path.sep.replace(/[.?*+^$[\]\\(){}|-]/g, '\\$&');`

**Comment by dopry** [comment]
@maoberlehner I added some tests, unfortunately the replace with the regex you provided was breaking the test for the posix path separator.

**Comment by dopry** [comment]
I think I completed everything on your review list, except the generalized escaping. I've got what I need working to scratch my itch, on the project this was blocking. If you have a regex you know to be working, happy to incorporate it or test alternatives on windows for you.

**Review by maoberlehner — APPROVED** [review]

**Comment by maoberlehner** [comment]
I looked up the [path.sep](https://nodejs.org/api/path.html#path_path_sep) documentation and I think it would be overkill to escape all regex characters.

To the push request looks fine now as it is.

**Pull request merged**
